// ve/src/App.vue
<template>
<main style=display:flex>
	<NavMenu />
	<div class=v-hr></div>
	<div>
		<router-view/>
		<CodeView />
	</div>
</main>
</template>

<style scoped>
.v-hr{
	margin: 0 10px;
	border-right: 5px solid #CCC;
	height: 98vh;
}
</style>

<script lang:ts>
import {Component,Vue} from "vue-property-decorator";
import NavMenu from "@/components/NavMenu.vue";
import CodeView from "@/components/CodeView.vue";

@Component({
	components:{
		NavMenu,
		CodeView
	}
})
export default class App extends Vue{}
</script>

// ng/src/app/app.component.ts
const template=`
<main style=display:flex>
	<NavMenu></NavMenu>
	<div class=v-hr></div>
	<div>
		<router-outlet></router-outlet>
		<CodeView></CodeView>
	</div>
</main>

<style>
.v-hr{
	margin: 0 10px;
	border-right: 5px solid #CCC;
	height: 98vh;
}
</style>
`;

import {Component} from "@angular/core";

@Component({
	selector: "app-root",
	template: template
})
export class AppComponent{}
