// ng/src/app/pages/P9_OnChangeEvent.component.ts
const template=`
<div>
	<h1>Check: {{isChecked}}</h1>
	<input id=chk type=checkbox [(ngModel)]="chkChange">
	<label for=chk>CheckBox</label>
</div>
`;

import {Component} from "@angular/core";

@Component({
	selector: "OnChangeEvent",
	template: template
})
export class OnChangeEventComponent{
	isChecked=false;

	get chkChange(){return this.isChecked;}
	set chkChange(value:boolean){
		this.isChecked=value;
		alert(`Check: ${this.isChecked}`);
	}
}

// ve/src/views/P9_OnChangeEvent.vue
<template>
<div>
	<h1>Check: {{isChecked}}</h1>
	<input id=chk type=checkbox v-model="isChecked" @change="chkChange">
	<label for=chk>CheckBox</label>
</div>
</template>

<script lang=ts>
import {Component,Vue} from "vue-property-decorator";

@Component
export default class OnChangeEvent extends Vue{
	isChecked=false;

	chkChange(){
		alert(`Check: ${this.isChecked}`);
	}
}
</script>
