// ng/src/app/components/BooksInput/BooksInput.component.ts
const template=`
<div>
	<div><textarea [(ngModel)]="bookList" id="bookList"></textarea></div>
	<button (click)="setBooks()">Set Books!</button>
</div>

<style>
#bookList{
	height: 300px;
	width: 300px;
}
</style>
`;

import {Component} from "@angular/core";
import {StoreService} from "../../store.service";

@Component({
	selector: "BooksInput",
	template: template
})
export class BooksInputComponent{
	constructor(
		private store:StoreService
	){}
	bookList=`たのしいさんすう
たのしいこくご
たのしいどうとく
かぐやひめ
シンデレラ
うらしまたろう
かちかちやま`;

	public setBooks(){
		this.store.books=this.bookList.split(/\r|\n|\r\n/).filter(s=>s!="");
		this.store.date=new Date();
		alert("setBooks!");
	}}

// ve/src/components/BooksInput.vue
<template>
<div>
	<div><textarea v-model="bookList" id="bookList"></textarea></div>
	<button @click="setBooks">Set Books!</button>
</div>
</template>

<style scoped>
	#bookList{
		height: 300px;
		width: 300px;
	}
</style>

<script lang=ts>
import {Component,Vue,Prop} from "vue-property-decorator";
import store from "@/store";

@Component
export default class BooksInput extends Vue{
	bookList=`たのしいさんすう
たのしいこくご
たのしいどうとく
かぐやひめ
シンデレラ
うらしまたろう
かちかちやま`;

	public setBooks(){
		store.commit("setBooks",this.bookList.split(/\r|\n|\r\n/).filter(s=>s!=""));
		store.commit("setDate",new Date());
		alert("setBooks!");
	}
}
</script>
